name: reusing_workflow

on:
  workflow_dispatch:

jobs:
  reusing_workflow_job:
    uses: bigdaz/test-gradle-build-action/.github/workflows/reusable-workflow.yml@main
    with:
      gradle-arguments: help
    secrets: inherit
